version: '3'

networks:
    amocrm:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../.:/var/www/html:delegated
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - amocrm

  postgres:
      container_name: postgres
      image: "postgres:12.2"
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 4aWvh75t
          PGDATA: /data/postgres
      volumes:
          - ./postgres/data:/data/postgres
          - ./postgres/scripts:/docker-entrypoint-initdb.d
      ports:
          - "5432:5432"
      networks:
          - amocrm
      restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./development.Dockerfile
      args:
        LOCAL_LINUX_USER: ${LOCAL_LINUX_USER:-0}
        LOCAL_LINUX_USER_UID: ${LOCAL_LINUX_USER_UID:-0}
    container_name: php
    volumes:
      - ../.:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - amocrm
